name: spider
description: A small dart command-line tool for generating dart references of assets from the assets folder.
version: 2.2.2
homepage: https://github.com/BirjuVachhani/spider

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.1
  yaml: ^3.1.0
  args: ^2.3.0
  dart_style: ^2.2.2
  logging: ^1.0.2
  watcher: ^1.0.1
  http: ^0.13.4
  html: ^0.15.0
  sprintf: ^6.0.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  build_version: ^2.1.0
  test: ^1.20.1
  lints: ^1.0.1
  mockito: ^5.1.0

executables:
  spider: main